### ISSUE TITLE
user added review

### ISSUE THREAD

**Issue by CKschneid** [CKschneid/redux-restaurant-review#1]
When a user review is submitted, an action type of 'ADD_REVIEW' is dispatched.  Since the store is updated, the redux-connected component ("RestaurantFullPageSuperContainer") should receive updated props (which will contain the new review to add to those already displayed) via mapStateToProps.  When the reselector function (findFeaturedRestaurant) is fired in this context it fails.  @hoodwink73

**Comment by CKschneid** [comment]
@hoodwink73

**Comment by hoodwink73** [comment]
There is problem in the reducer when `ADD_REVIEW` is dispatched. It resets all value for all restaurant items to `null`.

Will send the fix, possibly by today.
